### ISSUE TITLE
Can't create DBCode notebook

### ISSUE THREAD

**Issue by AtlantisWing** [dbcodeio/public#10]
When I click ctrl+shift+p -> DBCode: Create a new DBCode Notebook then alert a error message: Command 'DBCode: Create a new DBCode Notebook' resulted in an error  -- Cannot read properties of undefined(reading 'data')

**Comment by mikeburgh** [comment]
Thanks, will get that fixed in the release we are doing this week. 

In the meantime, if you need to open a new notebook, you can use the explorer and and the new notebook icon, detailed here: https://dbcode.io/docs/query/notebooks

**Comment by AtlantisWing** [comment]
thx a lot~~
https://dbcode.io/docs/query/notebooks
it's work~

**Comment by mikeburgh** [comment]
0.15.0 has been released, which contains this fix.
