### ISSUE TITLE
mysql introspection error

### ISSUE THREAD

**Issue by xenlata** [dbcodeio/public#100]
Error:
Unknown column 'INDEX_NAME' in 'window order by'

---
VSCode Version: 1.95.1
Extension Version: 1.3.18
OS: win32
Arch: x64
Database Version: MySQL Community Server - GPL - 8.0.11

**Comment by mikeburgh** [comment]
Interesting, it looks like the introspection script must be hitting a bug in MySQL as the column it's complaining about is there, it's just not using the alias I set on the table.

I just pushed a pre release version with some new DB's and a potential fix for this issue, can you install it and give it a try ?

**Comment by mikeburgh** [comment]
This fix is now in the main version just released, version 1.4. Does it work for you if you update to that version

**Comment by mikeburgh** [comment]
I am going to close this, re open if you are still having the issue.
