### ISSUE TITLE
Unable to download `better-sqlite3-multiple-ciphers`

### ISSUE THREAD

**Issue by 5macro** [dbcodeio/public#101]
The error shown up once using the sample database:
```
DBCode Network Error GET:https://github.com/m4heshd/better-sqlite3-multiple-ciphers/releases/download/v11.1.2/better-sqlite3-multiple-ciphers-v11.1.2-electron-v128-darwin-x64.tar.gz - UND_ERR_CONNECT_TIMEOUT: fetch failed
```

It turns out that the `better-sqlite3-multiple-ciphers-v11.1.2-electron-v128-darwin-x64.tar.gz` doesn't exist.

```bash
$ curl https://github.com/m4heshd/better-sqlite3-multiple-ciphers/releases/download/v11.1.2/better-sqlite3-multiple-ciphers-v11.1.2-electron-v128-darwin-x64.tar.gz
Not Found
```

version: `v0.16.1`

**Comment by 5macro** [comment]
Thanks @mikeburgh for helping out, yes it was fixed in the new version. I'm gonna close the issue.

**Comment by mikeburgh** [comment]
Did you get 0.16 from the marketplace awhile ago ? Or somewhere else recently, just want to make sure any places offering old versions get updated.

**Comment by 5macro** [comment]
> Did you get 0.16 from the marketplace awhile ago ? Or somewhere else recently, just want to make sure any places offering old versions get updated.

Not really, it's pretty weird that I installed the 0.16.1 a few days ago via the vscode extensions marketplace and have to install the latest one manually by `install the specific version`.

**Comment by mikeburgh** [comment]
Yeah that’s very strange!

Are you using vscode or one of the forks like cursor/pear/codium ?

**Comment by mikeburgh** [comment]
All good, I managed to replicate it myself, it has something to do with when there is a pre release version available. Raising it as a bug with MS, and will avoid pre releases until they fix it.
