### ISSUE TITLE
Error Apply changes

### ISSUE THREAD

**Issue by DIMANRUS** [dbcodeio/public#102]
Hello
![Image](https://github.com/user-attachments/assets/a2ebb973-3e07-490c-859a-bbb4994fc83b)

**Comment by mikeburgh** [comment]
Thanks, what were the data types you were editing / adding ?

**Comment by DIMANRUS** [comment]
I added row. In row varchar, bool, int.

**Comment by mikeburgh** [comment]
I tracked it down, fixed in 1.4 which is now released
