### ISSUE TITLE
More shortcuts please

### ISSUE THREAD

**Issue by ChromeGG** [dbcodeio/public#106]
Hi,

Would be nice to have more shortcuts defined OOTB. For example:
View: show DB Code: `CMD` + `SHIFT` + `B`
Or when we are on the results tab, `CMD` + `F` could focus the search input
![Image](https://github.com/user-attachments/assets/f6e5b593-08b5-4f27-8fd7-7f9cacc7033d)

Thanks :)

**Comment by mikeburgh** [comment]
It's the little details that make all the difference, and I can often miss em… keep em coming!

**Comment by mikeburgh** [comment]
I just pushed the cmd/ctrl f binding.

On the show DBCode one, are you thinking it would show the DBCode tab in the panel , or the explorer tree ?

The other issue I have for it is finding an empty shortcut, there are so many already taken… I can limit it by context like the execute one, but if the idea is to show something from anywhere in the editor that won’t work.

**Comment by ChromeGG** [comment]
Thanks for such a quick response, I really appreciate  that.

>On the show DBCode one, are you thinking it would show the DBCode tab in the panel , or the explorer tree ?

Explorer tree.
Yeah, right. I'll stick with my custom one then 😄

**Comment by mikeburgh** [comment]
What about the shortcut cmd+d cmd+b it's similar to the cmd+b shortcut, but uses the d b letters.. It's also not used by anything, and if there are other logical things to add later, they could come after the d b part..
