### ISSUE TITLE
SSH Tunnel with custom ssh key location

### ISSUE THREAD

**Issue by gihankarunarathne** [dbcodeio/public#108]
I tried connecting to a local MySQL database, and it's working perfectly. But I want to use this with real data.

Thus, I tried to connect to a remote database using SSH tunneling with Jump Hosting, and I set up the SSH tunnel as below.

![Image](https://github.com/user-attachments/assets/3ed56219-053b-4089-8d01-ff60d3cd5aa0)

Please note that I have multiple SSH keys set up and reading from the default SSH is not going to work for me.
Thus I choose the location such that `/Users/john/.ssh/org_id_rsa` on MacBook. But I'm getting the following error while trying to connect to the database.

![Image](https://github.com/user-attachments/assets/e673d8a9-667d-4254-9964-9a368cb257e0)

Could you help with this issue?

Q: Is it a good idea to allow the key path as plain text?

**Comment by mikeburgh** [comment]
I tried to replicate this, but I could not. The error you are getting is cause there is no private key configured for the tunnel, but when I try to create a tunnel with a key file as the authentication I cannot save it until I select a file.

Your screenshot shows no file selected ? Were you able to save it like that, or is that just a screenshot before you selected the key to not leak the path ?<br><br>If you were able to save it like that, I will try and replicate it, if not and you did select a file, can you share the tunnel config from settings.json (feel free to xx out the values of the keys)

You can find the configs if you search for dbcode.tunnels in the settings.json, here is an example, you can see the privateKey path is set, if I remove it, I get your error, but I can only do that by editing the settings json manually and making it invalid (authType key but no key

```json
{
			"id": "tv0Qq",
			"type": "ssh",
			"name": "Testing no Auth key",
			"host": "17.0.0.1",
			"port": 50017,
			"username": "foo",
			"authType": "key",
			"password": "",
			"savePassword": "secretStorage",
			"privateKeyPath": "~/.ssh/id_test_pwd"
			
		}
```

**Comment by gihankarunarathne** [comment]
>  The error you are getting is cause there is no private key configured for the tunnel

In my screenshot, the key was not selected. But I tried it after selecting the key.

Let me try the config.

---
Also, my SSH keys are in `.ssh` folder which is not showing on the file finder, which isn't the best customer experience, IMO.

**Comment by gihankarunarathne** [comment]
Also, I had to disable the extension for now because it exhausted my Copilot limits and caused a rate limit error from the Copilot.
I was editing a `.sql` file which has multiple MySQL code blocks. I was using `o1-preview` and suddenly got above issue (never face such issue before).

It would be great if there was an option to disable the suggestions without disabling the extension. I can setup a shortcut to make it faster.

**Comment by mikeburgh** [comment]
Can you check which version of the extension you are using? by chance is it 0.16.1 ? There was an issue last week where that was the version the marketplace was offering for download. It's very old, and use to not show the .ssh folder like you are describing. If you are on that version can you install the updated version via the extensions section (1.4.8).

Let me know if that does not fix the .ssh folder showing when selecting a key.

Having a password on the key is fine, the box under selecting the key is for that password.

I believe the rate limit you hit is per extension so it will have just effected DBCode's use of copilot not all of copilot.

01-preview has the lowest rate limit I think (MS does not disclose what it is). You can change the model in the DBCode settings section, or the command (cmd+shit+p) -> DBCode: Change AI Model. Although I agree, a setting to either not use co pilot and use our AI, or to disable inline completion totally makes sense, I will get that added.

Also your earlier question about storing the key path in plain text.. can you explain more your concern with that ? it's just a path to a file on the computer.  The password is encrypted (if you choose that option, and choose to store it)

**Comment by mikeburgh** [comment]
I just checked, there is a setting already in place to disable inline completion, it's in settings -> Extensions -> DBCode - AI section, or search for Inline Completion and you should find it to disable it.

I will leave this open to hear from you on the version and work through the tunnel issue.

**Comment by mikeburgh** [comment]
I am going to close this, re open if you are still not able to select the .ssh folder.
