### ISSUE TITLE
mariadb connection error

### ISSUE THREAD

**Issue by teamworkapac** [dbcodeio/public#110]
Error:
MariaDB 10.3.0 or higher is required.

---
VSCode Version: 1.95.2
Extension Version: 1.4.7
OS: win32
Arch: x64

**Comment by mikeburgh** [comment]
What version are you trying to connect to, at the moment we only support 10.3 and above.

**Comment by mikeburgh** [comment]
Going to close this, re open and I can look into it, but at this stage we don't support versions below 10.3
