### ISSUE TITLE
mongodb connection error

### ISSUE THREAD

**Issue by Bryan-Roe** [dbcodeio/public#119]
Error:
Server selection timed out after 30000 ms

---
VSCode Version: 1.95.3
Extension Version: 1.4.8
OS: linux
Arch: x64

**Comment by mikeburgh** [comment]
I just released version 1.4.9, can you try it and see if that fixes it?

If not I assume you can connect with the official mongo extensions ?

**Comment by mikeburgh** [comment]
Closing this, if it's still not working re open/comment and I can look into it further.
