### ISSUE TITLE
Can't filter/remove schemas out of explorer view

### ISSUE THREAD

**Issue by k3mist** [dbcodeio/public#12]
I can't see anywhere to filter out temp schemas for postgres. postgres creates A LOT of "temp" schemas. Particularly ones that start with `pg_temp` and `pg_toast_temp`. 

So the ability to filter from the explorer view with a wildcard or regex as a permanent setting would be greatly appreciated. 

here is what im referring to;

![image](https://github.com/dbcodeio/public/assets/439440/dc44b79f-cc1a-4e83-a44d-21b75a74f4e3)

**Comment by mikeburgh** [comment]
Wow, yeah that's a lot! 

I had originally planned to do something like this as a right click option on the schema.. but after seeing that list that does not seem as nice.

What about an option on the connection details (when you add/edit) to filter schemas, and it can default to something like pg_*, but you can change it if needed... and then it's central and easy to manage. 

Should they just hide, or do you want to maybe stick them in their own folder, so you could still get into them if you need to ? I am leaning towards their own folder, so they are not totally hidden.

**Comment by mikeburgh** [comment]
This has been added in 0.15.1. You can edit a connection and select the option for filter, and then control filtering schema (and databases). 

For now they are just totally hidden, pending feedback we might add an option to put them in their own folder.

**Comment by k3mist** [comment]
sorry for the late reply. this is greatly appreciated! thank you @mikeburgh!
