### ISSUE TITLE
Update your application id to add the Broker redirectUri if you haven't already

### ISSUE THREAD

**Issue by TylerLeonhardt** [dbcodeio/public#123]
Hello :wave: I'm Tyler from the VS Code team. We noticed that this extension overrides the built-in Microsoft authentication EntraID application id. We wanted to inform you that VS Code will start acquiring auth sessions from the OS via the [native token broker](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/brokering.md#acquiring-device-bound-tokens). On Windows, this will use WAM.

In order to support this and prevent downtime in your extension, all public client applications must include the broker redirectUri. Simply add this redirect Uri to your app registration in the Public Client section of the Azure portal:
```
ms-appx-web://Microsoft.AAD.BrokerPlugin/<your-client-id>
```

That's it! :tada: This will ensure that your extension continues to work seamlessly with the new authentication flow. If you have any questions or concerns, please don't hesitate to reach out to us. We're here to help! :smile:

**Comment by TylerLeonhardt** [comment]
In insiders you can test this, yes. Simply log out of your Microsoft account and log back in.

**Comment by mikeburgh** [comment]
Testing this out, adding that URI seems to have no impact, and it works with Insiders, or standard VSCode with or without it.

The only thing I did notice was that insiders uses the redirectURI: 
http://localhost:50238

While VSCode uses
https://vscode.dev/redirect

Is there something more at play here I need to test this ? I tried on a clean windows 11 install, without being signed into the OS and being signed into the OS.

**Comment by TylerLeonhardt** [comment]
You must be on x64 bit Windows and apply the setting:

```
"microsoft-authentication.implementation": "msal"
```

**Comment by mikeburgh** [comment]
Thanks, replicated and fixed.
