### ISSUE TITLE
Can I execute single queries in .sql file?

### ISSUE THREAD

**Issue by Damocod** [dbcodeio/public#128]
Hi. Great extension so far. Thank you.
Is there a way of running single queries not from a notebook but from a .sql file to output in the bottom panel BDCODE tab? I only see the option to execute the entire file.

**Comment by mikeburgh** [comment]
Thanks!

Yes, if you highlight the lines you want to execute… the code lens changes to execute selection and the key shortcuts and execution icon all reflect only executing the selected text

**Comment by Damocod** [comment]
Great. Thank you!
