### ISSUE TITLE
postgres introspection error

### ISSUE THREAD

**Issue by vagnerrods** [dbcodeio/public#129]
Error:
column "prokind" does not exist

---
VSCode Version: 1.95.3
Extension Version: 1.4.13
OS: darwin
Arch: arm64
Database Version: PostgreSQL 9.6.24, compiled by Visual C   build 1800, 64-bit - 9.6.24

**Comment by mikeburgh** [comment]
It appears 9.6 does not have the prokind field in the pg_catalog, looking at working around it..

**Comment by mikeburgh** [comment]
Yes, version 11 introduced procedures, before that it was only functions.. working on a fix for that.

**Comment by mikeburgh** [comment]
Fixed in 1.4.15
