### ISSUE TITLE
postgres connection error

### ISSUE THREAD

**Issue by sherckuith** [dbcodeio/public#131]
Error:
getaddrinfo ENOTFOUND localport

---
VSCode Version: 1.95.3
Extension Version: 1.4.13
OS: darwin
Arch: arm64

**Comment by mikeburgh** [comment]
Make sure the port is not in the same field as the host.. 

Can you share a screenshot of the connection?

**Comment by mikeburgh** [comment]
Closing this, re open if you are still having issues
