### ISSUE TITLE
mysql introspection error - Illegal mix of collations

### ISSUE THREAD

**Issue by DavidGCalles** [dbcodeio/public#132]
While i appreciate the warning, it should not be blocking me from inspecting the database. 

Error:
Illegal mix of collations (utf8_general_ci,COERCIBLE) and (utf8_spanish_ci,COERCIBLE) for operation '='

---
VSCode Version: 1.95.3
Extension Version: 1.4.14
OS: win32
Arch: x64
Database Version: (Google) - 8.0.26-google

**Comment by mikeburgh** [comment]
Agreed... I need to re work the MYSQL introspection, there are too many edge cases at the moment with various implementations and issues like this. Going to strip it back to plain selects. I will update this once done to see if that corrects the issue.

**Comment by mikeburgh** [comment]
I just released version 1.5.4 which now just uses plain select's to get the data from the database for the schema. Can you give it a try and see if fixes the issue for you ?

**Comment by DavidGCalles** [comment]
Works like a charm. I tried a lot of extensions and I feel yours is the
best, so many many thanks for this and your dedication
