### ISSUE TITLE
suggestion: reuse results tab when executing sql query

### ISSUE THREAD

**Issue by arc87** [dbcodeio/public#133]
add configuration in the extension that allows showing the result of the execution of a sql query in a single results tab

Currently we have this configuration but even with these settings the result of the query continues to be shown in several tabs

![Image](https://github.com/user-attachments/assets/9b0a29d5-7e4b-4857-9378-673f333672b3)
![Image](https://github.com/user-attachments/assets/f8108905-dc8d-44a5-87d8-9e844ff1518e)

**Comment by mikeburgh** [comment]
Looks like a bug, the panel is not seeing the updated setting, if you restart the extension it picks it up..

**Comment by arc87** [comment]
> Looks like a bug, the panel is not seeing the updated setting, if you restart the extension it picks it up..
Hi @mikeburgh is correct, restarting the extension applies the configuration and the result is displayed in a single tab

**Comment by mikeburgh** [comment]
Fixed in 1.4.15
