### ISSUE TITLE
Unable to stop Execution

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#137]
Hi Mike,

I encountered an issue while working with the DBCode. When I close the execution result tab, it closes successfully. However, when I try to stop the execution itself, it continues running, and I am unable to stop it.

I’ve attached a screen recording for your reference to help demonstrate the problem.
https://github.com/user-attachments/assets/bfbe5b95-7146-4b8e-926a-603dc6777c5f

Looking forward to your assistance in resolving this.

Best regards,
Pradeep

**Comment by mikeburgh** [comment]
I cannot replicate this.

Some drivers don't support Cancelling, but maria/mysql does.. and in my tests it works.

Can you try running this and see if cancel works ?  It should give you 5seconds to cancel it

```sql
SELECT 	SLEEP(5.5);
```

**Comment by devpkr1** [comment]
`SELECT SLEEP(5.5);` this statement  works and cancels successfully as expected. 

However, as shown in the attached screen recording, I am unable to cancel this `select * from deposit_data;` statement only in maria DB , this statement executed successfully with MySQL database.

DBCode Screen recording :- https://github.com/user-attachments/assets/efc6d306-2fa5-422c-a556-5a1d68bda47e

For reference, I have also included a screen recording demonstrating the same statement executed within Navicat and DataGrip, where it works without any issues.

Navicat screen recording :-  https://github.com/user-attachments/assets/70b2c07a-6d34-46b1-844a-402ae2b415f7
Datagrip Screen recording :- https://github.com/user-attachments/assets/bd7edf0e-1407-4380-b9fc-4796c86f006b

Kindly look into this matter and let me know if further details are needed.

Thank you for your assistance.

Best regards,
Pradeep

**Comment by mikeburgh** [comment]
Okay so this is not actually a problem with cancel, the execution has long finished so there was nothing to cancel. 

It was a rendering issue with those 0000-00-00 dates that MySQL lets you store. I added some handling for those, should be fixed in 1.5.3 which is now released

I also made some changes to try and better surface these errors so you can see them and open issues for them when they happen.
