### ISSUE TITLE
API Network Error POST:jwt - SELF_SIGNED_CERT_IN_CHAIN: fetch failed

### ISSUE THREAD

**Issue by gene-github** [dbcodeio/public#14]
I cannot access my account, nor get the appropriate license. I'm using WSL.  

Here is the error message:

API Network Error POST:jwt - SELF_SIGNED_CERT_IN_CHAIN: fetch failed

Please solve this problem.

**Comment by gene-github** [comment]
![DBCode - 2024-08-07_16-08-22](https://github.com/user-attachments/assets/bc565cba-996a-4c82-af56-81c941e2d575)

**Comment by gene-github** [comment]
![DBCode - 2024-08-07_16-08-22](https://github.com/user-attachments/assets/04529adb-4118-45b9-b049-3d3e478081eb)

**Comment by mikeburgh** [comment]
Can you post the recent log lines from the output tab, choose DBCode from the drop down top right of the output panel. Feel free to remove any  details you don't want to share publicly from the output.. it will contain the steps shown leading up to this.

In the meantime, you can switch back to version 0.17.1... and see if that solves it ? You can do that via the extensions explorer, click the settings icon for DBCode, and choose the install specific version option.

**Comment by gene-github** [comment]
2024-08-07 16:39:00.123 [info] Connection: using cache for 'xxx' on 'XXXX'
(refreshing in background)
2024-08-07 16:39:05.953 [info] Signed in as 'github_id' with 'GitHub'
2024-08-07 16:39:06.297 [error] API Network 'POST:jwt' -
SELF_SIGNED_CERT_IN_CHAIN:fetch failed
2024-08-07 16:39:06.298 [info] Signed out 'github_id' with 'GitHub'
2024-08-07 16:39:57.526 [info] Signed in as 'github_id' with 'GitHub'
2024-08-07 16:39:57.689 [error] API Network 'POST:jwt' -
SELF_SIGNED_CERT_IN_CHAIN:fetch failed
2024-08-07 16:39:57.689 [info] Signed out 'github_id' with 'GitHub'
2024-08-07 16:40:00.516 [info] Signed in as 'github_id with 'GitHub'
2024-08-07 16:40:00.665 [error] API Network 'POST:jwt' -
SELF_SIGNED_CERT_IN_CHAIN:fetch failed
2024-08-07 16:40:00.666 [info] Signed out 'github_id' with 'GitHub'

**Comment by gene-github** [comment]
I am trying to sign in to my account to purchase a license, and it seems to
me that it errors out.  As soon as it signs me in, the app
immediately signs me out.  Again, I am not sure if that is the issue with
my WSL environment.  I can access outside from inside of my WSL/Ubuntu out
no problem.  It seems to me that it is VsCode's extension (DBCode) fails.

**Comment by gene-github** [comment]
Full log:

2024-08-07 16:39:00.078 [info] DBCode starting...
2024-08-07 16:39:00.078 [info] DBCode started
2024-08-07 16:39:00.078 [info] Connection: Restored mapping for 'xxx.sql'
2024-08-07 16:39:00.079 [info] Connection: Restored mapping for 'xxx.sql'
2024-08-07 16:39:00.079 [info] Connection: Restored mapping for
'call_xxx.sql'
2024-08-07 16:39:00.079 [info] Connection: Restored mapping for 'xxx.sql'
2024-08-07 16:39:00.079 [info] Connection: opened 'xxx' on ***@***.***'
2024-08-07 16:39:00.123 [info] Connection: using cache for 'xxx' on ***@***.***
' (refreshing in background)
2024-08-07 16:39:05.953 [info] Signed in as 'xxx-github' with 'GitHub'
2024-08-07 16:39:06.297 [error] API Network 'POST:jwt' -
SELF_SIGNED_CERT_IN_CHAIN:fetch failed
2024-08-07 16:39:06.298 [info] Signed out 'xxx-github' with 'GitHub'
2024-08-07 16:39:57.526 [info] Signed in as 'xxx-github' with 'GitHub'
2024-08-07 16:39:57.689 [error] API Network 'POST:jwt' -
SELF_SIGNED_CERT_IN_CHAIN:fetch failed
2024-08-07 16:39:57.689 [info] Signed out 'xxx-github' with 'GitHub'
2024-08-07 16:40:00.516 [info] Signed in as 'xxx-github' with 'GitHub'
2024-08-07 16:40:00.665 [error] API Network 'POST:jwt' -
SELF_SIGNED_CERT_IN_CHAIN:fetch failed
2024-08-07 16:40:00.666 [info] Signed out 'xxx-github' with 'GitHub'

**Comment by mikeburgh** [comment]
Thanks, you are correct,  the sign in stage works... it then tries to get a token from our site via HTTPS and is getting an error that there is a self signed certificate being used. 

In the terminal in VScode (which should be your WSL/Ubuntu environment, can you run: 

```bash
curl -sS -v -D - https://dbcode.io -o /dev/null
```

and share the results... this should show the handshake and SSL details when attempting to connect to our site.

Are you using a VPN, proxy, or on a corporate network ? Sometimes corporate networks use self signed certs to be able to intercept all network traffic for compliance/monitoring reasons. 

A report I just ran for the site shows everything is fine with the certificates in place: https://www.ssllabs.com/ssltest/analyze.html?d=dbcode.io

**Comment by gene-github** [comment]
❯ curl -sS -v -D - https://dbcode.io -o /dev/null
*   Trying 76.76.21.21:443...
* TCP_NODELAY set
* Connected to dbcode.io (76.76.21.21) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [75 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [3557 bytes data]
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
} [2 bytes data]
* SSL certificate problem: self signed certificate in certificate chain
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate in certificate
chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.



MY RESPONSE:

We are using VPN via corporate network.

**Comment by mikeburgh** [comment]
Thanks, so that confirms it, the vpn/corporate network is using a self signed cert to intercept requests... I assume something like this also fails when run from the terminal under WSL (eg all WSL requests fail):

```bash
curl -sS -v -D - https://google.com -o /dev/null
```

I assume in windows you can browse to https://dbcode.io without issue ? 

For now stick with 0.17.1, we might have to add an option to manually provide the key it's trying to fetch.

**Comment by mikeburgh** [comment]
I did some looking into this, it seems like a fairly common issue that presents in a few different cases... https://github.com/microsoft/vscode/issues/131836 and https://github.com/microsoft/WSL/issues/3161 for example.

From reading, it looks like this approach might work for you, it basically copies the self signed certs from windows into WSL, and then updates WSL to see them https://github.com/bayaro/windows-certs-2-wsl

**Comment by gene-github** [comment]
Thank you.  Reviewing your response.

**Comment by mikeburgh** [comment]
@gene-github Did that fix work for you ?

**Comment by gene-github** [comment]
> @gene-github Did that fix work for you ?

Nope, it did not.

**Comment by gene-github** [comment]
> @gene-github Did that fix work for you ?

After following the above recommendations, it solved my problelm.  The certificate ca-certificates was missing from my /usr/... directory.  After copying it from /etc directory location to my /usr directory, everything worked.  I run curl test against google and it worked too.  Thanks!

**Comment by mikeburgh** [comment]
No worries, glad it worked!
