### ISSUE TITLE
Issue with Fixed Output Height in DBCode Notebook (Version 1.5.2)

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#144]
Hi Mike,

After updating to Version 1.5.2, I noticed an issue with the DBCode notebook. When executing any statement, the result/output is displayed with a fixed height, regardless of the number of rows in the result.

This behavior is quite inconvenient, as I have to scroll excessively to locate the next code cell, especially when the output is short. It disrupts the workflow and impacts usability.

I’ve attached a screen recording for reference. Please let me know if there’s a way to resolve this or if a fix is being planned.

https://github.com/user-attachments/assets/52f4db1e-4dbe-413f-b327-42557a03a798

Looking forward to your response.

Best regards,
Pradeep

**Comment by mikeburgh** [comment]
Indeed, fixed in 1.5.3 which is now released.
