### ISSUE TITLE
mysql introspection error

### ISSUE THREAD

**Issue by max-ep** [dbcodeio/public#145]
Error:
Illegal mix of collations (utf8mb3_general_ci,COERCIBLE) and (utf8mb3_unicode_ci,COERCIBLE) for operation '='

---
VSCode Version: 1.95.3
Extension Version: 1.5.2
OS: darwin
Arch: arm64
Database Version: Percona Server (GPL), Release '26', Revision '0fe62c85' - 8.0.34-26

**Comment by mikeburgh** [comment]
I just released version 1.5.4 which has a new introspection model I have been working on, trying it out on MySQL/Maria first as it has the most number of issues with the current way.<br><br>Can you let me know if it works for you now once you update to that version.

**Comment by mikeburgh** [comment]
Closing this as I had confirmation in the other issue it's fixed. If it's not for you, please re open
