### ISSUE TITLE
redshift introspection error

### ISSUE THREAD

**Issue by Bapu-Jadhav-lion** [dbcodeio/public#146]
Error:
Bad control character in string literal in JSON at position 529 (line 1 column 530)

---
VSCode Version: 1.96.0
Extension Version: 1.5.4
OS: win32
Arch: x64
Database Version: PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.80009 - Redshift 1.0.80009

**Comment by mikeburgh** [comment]
I just released version 1.5.5 which moves Redshift to the new introspection model I have been working on. Should solve this issue, if not re open this and I can do some more digging.
