### ISSUE TITLE
Copilot : not add double quotation marks

### ISSUE THREAD

**Issue by lyj0309** [dbcodeio/public#154]
![Image](https://github.com/user-attachments/assets/f9a46621-fc0b-419b-980b-0534339f1bde)

Double quotes (") are for case-sensitive database object names (tables, columns)

**Comment by mikeburgh** [comment]
Good find, I have tweaked it cover that when required!

It over quotes the identifiers now in Postgres (ones that don't need it) but I cannot seem to get a prompt that works around that, and at least being quoted it wont break.

Will update this when the fix is live.

**Comment by mikeburgh** [comment]
Fixed in the latest version
