### ISSUE TITLE
mysql introspection error

### ISSUE THREAD

**Issue by vitas1648** [dbcodeio/public#155]
Error:
Unknown column 'generation_expression' in 'field list'

---
VSCode Version: 1.95.1
Extension Version: 1.5.7
OS: linux
Arch: x64
Database Version: MySQL Community Server (GPL) - 5.6.39

**Comment by mikeburgh** [comment]
Thanks for raising, fixed in 1.5.8 which I just released. The new model for introspection means I can support these older versions.
