### ISSUE TITLE
ODBC Connections

### ISSUE THREAD

**Issue by sgpeter1** [dbcodeio/public#16]
Might I suggest considering ODBC connections? Almost every database has an ODBC driver and often decent instructions on configuring them. Could open doors to a lot of databases that could be difficult to develop for otherwise.

**Comment by mikeburgh** [comment]
Thanks for the suggestion.. 

At some stage we will probably add a generic ODBC to pick up the long tail of databases that we don't support natively.

Our preference for now is to add them directly since we can target their specific functionality and features vs the more generic approach of ODBC.

For example MySQL does not support the CREATE OR REPLACE syntax so we handle that by running a drop command (confirming with the user first) when updating a proc.. vs the databases that support CREATE OR REPLACE.

Is there a specific database you are looking for at the moment to be supported ? we have a few more on our list we are working through (BigQuery, Oracle, Clickhouse, Snowflake, Redis, and a few others)

**Comment by sgpeter1** [comment]
Thanks for your response!

Redshift and Oracle are the databases in current use at my organization.

Our Oracle configuration is quirky, though. ODBC and JDBC are the only surefire ways to connect because of some peculiar authentication requirements that aren’t supported in the modern libraries (python, etc.). It’s an odd thing, but we live with it.

**Comment by mikeburgh** [comment]
No worries, let me see if we can get those pushed up a bit.. Oracle has been on the list of awhile, last of the majors.. 

Do you mind sharing the auth requirements you have? Just so we can keep an eye out for them when adding it and see if we cannot pick them up rather than using ODBC. I know the oracle extension for VSCode uses the java client and ships a JDK to run it.. would like to avoid that unless there is no other options.

**Comment by sgpeter1** [comment]
When using python, we have to use "thick" mode and the separately-installed Oracle Client Libraries (as the libraries support the older authentication method in use at my org). I suppose if you could support "thick" mode for those who have the Oracle Client Libraries installed, that might do it. See the [node][1] and [python][2] Oracle driver documentation regarding it.

There are actually two Oracle VScode extensions. One uses an embedded JVM (SQL Developer) and the other (Developer Tools) probably uses the Oracle node driver (not sure).

[1]: https://node-oracledb.readthedocs.io/en/latest/user_guide/appendix_a.html
[2]: https://python-oracledb.readthedocs.io/en/latest/user_guide/initialization.html

**Comment by mikeburgh** [comment]
Thanks, will check out those options shortly.

We just pushed out redshift support in version 1.2.0. Was a bit of a challenge with some of the modern PG features not being supported, but should be good to go. Would you mind giving it a try and letting us know how it goes ?

**Comment by sgpeter1** [comment]
Excellent, thank you. Happy to test Redshift. I'll open separate tickets for any issues. :)

**Comment by mikeburgh** [comment]
Making some progress with Oracle.. theres a lot to the connection options, once I get it sorted with thick clients, are you interested in giving it a test ?  

<img width="442" alt="Screenshot 2024-09-30 at 4 05 13 PM" src="https://github.com/user-attachments/assets/9fbeb100-da6e-4db1-bdd5-337ec0906393">

**Comment by sgpeter1** [comment]
Sure, happy to test Oracle when it's ready.

**Comment by mikeburgh** [comment]
Thanks!

I just pushed a pre release version, if you locate the extension there should be an option to switch to using the pre release.

Oracle is there marked as Beta... At this stage... really just looking for feedback on if you can connect (with the auth requirements you have) and if the options make sense. 

You can choose to connect with a host/port/service name combo, or connection string.. I belive the connection string will support TNS(?) alias if you use the instant client.

Either connection mode should work with the instant client.

Once you do connect, only limited introspection at the moment, just the list of schemas, tables and views.

**Comment by sgpeter1** [comment]
Hello,

Just tried this every which way was I could and couldn't get a connection. Oracle connection can be finicky, in my experience. It's throwing this error:

ORA-12154: TNS:could not resolve the connect identifier specified

That said, I have no problem running this code snippet with node (assuming that's what you're using):

```javascript
const oracledb = require('oracledb');
oracledb.initOracleClient();

oracledb.outFormat = oracledb.OUT_FORMAT_OBJECT;

const mypw = "..."  // set mypw

async function run() {

    const connection = await oracledb.getConnection ({
        user          : "myusr",
        password      : mypw,
        connectString : "internalrac"
    });

    const result = await connection.execute(
        "select * from hr.dummy fetch first 5 rows only"
    );

    console.log(result.rows);
    await connection.close();
}

run();
```

All that said, as previously noted, my organization's connection setup is peculiar and likely not worth developing towards.

Thanks!

**Comment by mikeburgh** [comment]
Okay so it's finding the instant client, but then cannot resolve the connection string TNS for some reason..

Yes, code is node (all of VSCode is unless you get funky and do things with WASM or node binaries). 

I think I see the issue, will push a new pre release in a few hours.. just working through more the oracle introspection and discovering the joys of invalid procedures and functions.

All good, Oracle is a major DB, so always planned to get it supported... It's a beast though, so not sure just how much of it will end up in the product.. I do love it's dynamic functions in SQL though!

**Comment by mikeburgh** [comment]
Okay, a new pre release version is out.. connection should work now.

Introspection is largely done, but it's slow if you login as a system level account, and hits some errors if you don't have system level privileges.. so working through the best way to handle that combo.

Saving procs is also not working, and weird issues going on around the trailing semicolons.. but it's closer.. would still regard it as beta for anything that's not a user entered query.

would you mind shooting me an email at help@dbcode.io I have some questions around oracle and what makes sense to show in terms of schema's, objects.. don't want to clutter up the issue.. will give you a free sub, or credit one you have for your time and all the testing so far :)

**Comment by mikeburgh** [comment]
Closing this now we have the connection working with the thick client
