### ISSUE TITLE
Unable use Cloudflare D1

### ISSUE THREAD

**Issue by KayLeung** [dbcodeio/public#176]
<img width="854" alt="Image" src="https://github.com/user-attachments/assets/8fc24764-bce6-4a97-b9f5-6d849b9a32ed" />

This is connected as the image shown. When double-click to open the table, it shows auth issues.

I'm using a "Read all resources" API token.

**Comment by mikeburgh** [comment]
Just following up, did you figure this out or is it still an issues ?
