### ISSUE TITLE
Unable to connect to `127.0.0.1` on `code-server`

### ISSUE THREAD

**Issue by bilogic** [dbcodeio/public#19]
1. This plugin installs correctly on https://github.com/coder/code-server
2. Briefly, code-server runs on the remote OS and I access the VSCode offered by code-server via a URL in Chrome
3. `127.0.0.1` works on other DB plugins, e.g. https://github.com/cweijan/vscode-database-client
4. Instead, I have to specify the private IP in order to connect
5. Reason is because some of my databases are configured to only accept local connections

**Comment by mikeburgh** [comment]
So trying to understand the issue.. is that you have to enter the private IP (eg a 192.xxx or a 10.xx) in the connection, and you instead want to use the localhost (127.0.0.1) ? 

My understanding is this is similar to using vscode.dev and the tunnels feature... The extension is not running locally (eg it cannot as it's a web page), but on the remove server (eg where code-server is running or for vscode.dev where your tunnel is connected).

So the IP you enter for the host is based on that remote location, and provided the server/tunnel has the database on it, then 127.0.0.1 should work.. But it's not for you ?

**Comment by bilogic** [comment]
Yes to both your questions.

1 thing I will add is, I'm trying to use 127.0.0.1 and not localhost does not work as the remote database is running in a docker container. For some reason, only 127.0.0.1, using the string "localhost" won't work.

**Comment by mikeburgh** [comment]
Interesting, I setup a code-server install on my machine which means I am using the same outbound IP to connect to the database servers as though I was using VScode desktop app.

But when I try via code server to connect to Maria/MySQL I get an error like this: 

Connection Error: Error during pool initialization: (conn:387, no: 1045, SQLState: 28000) Access denied for user 'mike'@'10.x.x.xxx' (using password: YES) (pool connections: active=0 idle=0 limit=10)

However same exact connection details, works fine in the desktop. 

I assume you are connecting to Maria/MySQL db?

**Comment by bilogic** [comment]
![image](https://github.com/user-attachments/assets/8f16d32d-4ab0-4cdb-a69a-7e08222e8bd5)

Yes, it happens on both MySQL and Maria, but not access denied.

`Error connecting to 113, error: (conn:-1, no: 45028, SQLState: HY000) retrieve connection from pool timeout after 31000ms (pool connections: active=0 idle=0 limit=10)`

**Comment by mikeburgh** [comment]
Okay I have been able to replicate it.. but it's strange.

My docker logs show: 
2024-09-13 10:53:54 2024-09-13 17:53:54 223 [Warning] Access denied for user 'root'@'192.168.65.1' (using password: YES)

Yet the access is granted in the user table.. but what's more strange, is when I connect form VSCode desktop, I can see the connection from that same IP that's getting blocked..

 select id, user, host, command  from information_schema.processlist;
+-----+------+--------------------+---------+
| id  | user | host               | command |
+-----+------+--------------------+---------+
| 222 | root | 192.168.65.1:39536 | Sleep   |
|  31 | root | localhost          | Query   |
+-----+------+--------------------+---------+

Do you see any auth errors in your docker log ? 

I also fixed an issue with the MySQL connector, to speed up these errors rather than waiting for timeouts.

**Comment by bilogic** [comment]
I don't think it's a bug on your end. If you change the `localhost` in the record to `%`, you should be able to connect. Looking forward to your release. Thank you!

**Comment by bilogic** [comment]
I think `localhost` in the record means your PHP code etc connects using "localhost", and "127.0.0.1" is not "localhost". Something along this line.

**Comment by mikeburgh** [comment]
Yeah, I think I got a fix that will work, just waiting on a few other things, and I will push it later today.

Here is a video in code_server, running the container and then connecting to it... ( I have to fix that connection UI on smaller screens)

https://jmp.sh/ISD2XNQs

**Comment by mikeburgh** [comment]
Version 1.2.2 is now out, let me know if it fixes this issue for you.

**Comment by bilogic** [comment]
![image](https://github.com/user-attachments/assets/04afcebe-9bf1-43ec-9304-1d49455d3e21)

I get a new error for `127.0.0.1`, any ideas?

**Comment by mikeburgh** [comment]
Ahh, so that was always the error but the previous timeout was masking it.

At present I had not added support mutual cert auth (or whatever they call it)

Should be able to add that in early next week..

**Comment by bilogic** [comment]
Wonderful! Thank you!

**Comment by mikeburgh** [comment]
I just pushed 1.2.3.. it has a new option for MySQL connections, which is enabled by default, to allow fetching the public key if required..  Should fix that issue for you

**Comment by bilogic** [comment]
Yes working now, will close this issue then. Thank you so much!
