### ISSUE TITLE
mysql introspection error

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#24]
Error:
Illegal mix of collations (utf8mb4_0900_ai_ci,COERCIBLE) and (utf8mb4_unicode_ci,COERCIBLE) for operation '='

---
VSCode Version: 1.93.1
Extension Version: 1.2.8
OS: win32
Arch: x64

**Comment by mikeburgh** [comment]
Interesting.. would you mind running the following query and sharing the results ?   Also which version of MySQL are you using ? (I need to get that information added to the default ticket template)

```sql
SELECT 
    TABLE_SCHEMA
    , TABLE_NAME
    , TABLE_COLLATION 
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'information_schema'
```

**Comment by devpkr1** [comment]
Result of the query is attached as CSV file

and the MySQL version : -  MySQL 9.0.1

**Comment by mikeburgh** [comment]
Looks like github did not pick the attachment up.. you can email it to help@dbcode.io and I can get it from there.

**Comment by mikeburgh** [comment]
Thanks, I got the file. I was not expecting the collation columns to be null.. interesting. 

I just pushed a pre release version, can you switch to it and see if it fixes the issue for you ?

**Comment by devpkr1** [comment]
Hi mikeburgh,

Yes it fixes the issue , it's working for me now.

Thanks for your kind support.

Regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
Great, will close this ticket now.. a regular release will be out later this week which will include this fix.
