### ISSUE TITLE
Format SQL query option not available

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#26]
Hi DB code team,

I am using your vs code extension , its awesome having amazing features but i have noted that there is no option to format sql query written in notebook cells.

I have also noted that there is no option to save notebook as HTML for sharing purpose and for integration in a website.

Please add these features, it will make this extension more user friendly.

Thanks and Regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
A new pre release version is now out, formatting is in it if you want to check it out..

**Comment by devpkr1** [comment]
Yes , its working now.

**Comment by mikeburgh** [comment]
This is now in the main release 1.2.14
