### ISSUE TITLE
`CURRENT_TIMESTAMP` not working for MySQL when creating records for datetime

### ISSUE THREAD

**Issue by bilogic** [dbcodeio/public#27]
![image](https://github.com/user-attachments/assets/3f86b853-5eb9-4c63-8569-280f4392f3bc)

Can add this? 

Both `CURRENT_TIMESTAMP` and `CURRENT_TIMESTAMP()` fails. Thanks.

**Comment by mikeburgh** [comment]
Ahh, good find.. yeah that's going to be tricky to find all the function keywords for various things.. and not wrap them.. Will get the obvious ones added this week!

**Comment by mikeburgh** [comment]
This has been released in 1.2.14. 

When you edit a date column you will get an autocomplete for it, you can also enter it manually.. and it will be correctly handled in the change script that's applied to the database.
