### ISSUE TITLE
Toolbar in Output is not displayed correctly

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#28]
Hi DB Code Team,

Toolbar in Output is not visible in light themes, please resolve it .
Themes name :-
Light Modern Default
Github Light Default

![Screenshot 2024-10-03 103052](https://github.com/user-attachments/assets/3c8cb9f6-0939-467f-952f-a6db7d5ac536)

**Comment by mikeburgh** [comment]
Submitted up stream, https://github.com/vscode-elements/elements/issues/172 will look at a fix and submit a PR if I figure it out

**Comment by devpkr1** [comment]
ok

**Comment by mikeburgh** [comment]
This is now fixed in 1.2.14
