### ISSUE TITLE
Copy Selection button is not working in query output

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#32]
Hi mike , 

I have found another bug **copy selection** button is not working in query output , it is not copying anything from output.

screenshot attached:-

![Screenshot 2024-10-06 003619](https://github.com/user-attachments/assets/bb9ad03f-d4bb-4254-ba84-072ffa91c97c)

Thanks and Regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
It looks like you have grouped/pivoted the data, correct?

Can you confirm it works with the normal table ?

**Comment by devpkr1** [comment]
I didn't check it for the normal table but one thing I have noted is that
except this button all other buttons for copy  like " Copy selected rows"
are working fine.

**Comment by devpkr1** [comment]
Hi mike, 

This issue is also fixed after you pushed this pre-release.

Thanks and Regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
👍
