### ISSUE TITLE
postgres connection error

### ISSUE THREAD

**Issue by andriy-klmts** [dbcodeio/public#33]
Error:
getaddrinfo EAI_AGAIN postgres

---
VSCode Version: 1.94.0
Extension Version: 1.2.14
OS: linux
Arch: x64

**Comment by mikeburgh** [comment]
The host name you are using cannot be resolved... if Postgres is running in docker on your local machine the host should be localhost

**Comment by mikeburgh** [comment]
Closing this, if you are still having issues re open it.
