### ISSUE TITLE
Grid Lines enabled/disabled selection is not working in Column/Bar Charts

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#34]
Hi Mike,

I have found new bug in visualization of bar/column charts, grid lines enabled/disabled selection is not working properly.
Please look into this, I am attaching the screen recording.

https://github.com/user-attachments/assets/430e41aa-5afd-4fab-b117-4b30cadebae3

Best Regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
Confirmed, it's a bug in the chart lib.. when I upgrade to the latest version will test if it still happens, and if so raise it upstream... hopefully they have already fixed it and #30

**Comment by devpkr1** [comment]
Yeah , it is solved after update.

Thanks and Regards,
Pradeep Kumar
