### ISSUE TITLE
Decimal Data type is treated as String in Query Result  (For MySQL/Maria DB)

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#35]
Hi mike,

I have clearly found that decimal data type is treated as string type in query result that's why when i was used aggregation on a numeric column in select statement it shown string type in output result . This happens only with MySQL and Maria DB.

For your reference , i am attaching the screenshot. Please resolve this issue.

![Screenshot 2024-10-07 005017](https://github.com/user-attachments/assets/7c6787a9-9c44-4a1c-8dc3-0a06a6dfd35b)

Best Regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
Good find.. I missed it...  I force all the drivers to send back numbers as strings, to avoid the JS number limits issue and rounding that it causes...  but then the grid was still seeing them as strings. 

Fixed now, version 1.2.16 should have this sorted.. both in the column headings, and the charts.
