### ISSUE TITLE
Icons and menu enhancement required in Output result

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#37]
Hi mike,

I am excited to share a new enhancement suggestion that I believe will improve the UI of the output result. Upon reviewing the current output, I have noticed that a few menus and icons are missing. I have taken a screenshot to highlight these gaps.

![Screenshot 2024-10-07 141521](https://github.com/user-attachments/assets/4f02bc9b-699b-46ce-b9dd-e46d5fdb015b)

Thanks & regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
Great suggestions.. 

Open in new window.. I was thinking about either letting people drag the tab up to the main tabs area in the UI.. so could add a right click option to do it.. It would not be a new vscode window though.. just a new tab in the "main" area. Is that what you were thinking ? 

The view in fullscreen.. do you see that as being in full screen in the tab/area it's open in (eg covering the grid) or full screen as in a new tab like the above for the main tab ?

**Comment by devpkr1** [comment]
Yeah, it's a new tab, you add this option in the right click menu and for
chart visuals u can also add this feature to open in a new tab for full
screen view.

Thanks and regards

**Comment by mikeburgh** [comment]
The menu for the chart has been reworked in 1.3.15 and now has an expand/shrink option..  I will create a new issue for the open in new window from the results as it's more involved.
