### ISSUE TITLE
ERD - Export to PDF

### ISSUE THREAD

**Issue by mikeburgh** [dbcodeio/public#38]
Ability to save the in PDF format

**Comment by mikeburgh** [comment]
@DIMANRUS I just pushed a pre release version of this, supporting both PDF and PNG downloads, if you want to have an early look. 

Will probably hit the regular release next week.

**Comment by DIMANRUS** [comment]
> @DIMANRUS I just pushed a pre release version of this, supporting both PDF and PNG downloads, if you want to have an early look. 
> 
> Will probably hit the regular release next week.

Thanks

**Comment by mikeburgh** [comment]
Released in 1.4.6
