### ISSUE TITLE
Filter DB Explorer

### ISSUE THREAD

**Issue by DIMANRUS** [dbcodeio/public#42]
Hello. I would also like to see such an opportunity as searching among tables, procedures and other things when the focus is in the panel where the connections are. Here is an example from DataGrip. Thanks.
![image](https://github.com/user-attachments/assets/0e98b241-16b7-41b4-aaa3-2466e4ce1df7)

**Comment by mikeburgh** [comment]
VSCode has this built in for tree's.. 

If you press Mac: option+cmd+f  Windows: ctrl+alt+f when focused on the tree it should let you filter.

I build a custom one for the history tree, as the built in one only filters what's been expanded.

Does the built in one work for you, or do you need something more ? 

If it does what you need, I can look at maybe making it more obvious with the filter icon opening it..

**Comment by DIMANRUS** [comment]
Thanks for the reply. Yes, it works great for me, as in DataGrip. But it would be even better if I didn't have to expand the groups. For example, if I have an active connection to MSSQL, then in hidden state it would search all tables, procedures, views and give only them in the search

**Comment by mikeburgh** [comment]
Yeah now it's coming back to me, same reasons we did the custom one in history.. built in one wont expand things, and also doesn't filter out non matches..

**Comment by mikeburgh** [comment]
Just released 1.3 with this in place, let me know what your thoughts are.

some comments: 
1. No way to get to the find box VScode uses to filter, so have to use the larger input
2. There is a weird edge case where sometimes root elements are not expanded, still digging through the vscode to find where it is and possibly fix up stream

**Comment by DIMANRUS** [comment]
Hello. It searches well, but it is inconvenient that the search will be after pressing enter, and not immediately. As I understand it, this is impossible from the VSC side (as written in point 1) and performance. Thanks for this feature.

**Comment by mikeburgh** [comment]
Yeah at the moment it's not possible.. there is no on key press from that input (there is a validate method, but it's not consistent).

I fixed the reveal issue this morning, also got it working with cloud providers.

Until they open up api access to the find widget in the tree  this is probably as good as it's going to get.

**Comment by mikeburgh** [comment]
Version 1.3.2 is out, which tidies up the last few items
