### ISSUE TITLE
Request to Update File Extension for Notebooks

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#43]
Dear Mike,

I hope this email finds you well.

I would like to kindly request a change in the file extension for notebooks. Currently, the extension is **.dbcode**, which seems to represent the name of your VS Code extension. However, I believe a more appropriate and intuitive file extension for notebooks would be **.dbcn** or **.dbcnb**.

For comparison, when using **Jupyter notebooks, the extension is .ipynb, not .jupyter**. Similarly, for Excel files, the extension is .xlsx. **Following this convention, .dbcn or .dbcnb** would better reflect the nature of the files rather than the name of the extension.

Thank you for considering this suggestion. I look forward to hearing your thoughts on this.

Best regards,
Pradeep Kumar

**Comment by devpkr1** [comment]
Thank you for your prompt consideration! I'm glad you agree with the change to .dbcnb. Running both extensions for a while to allow people to switch over sounds like a great plan.

I appreciate your flexibility and look forward to the updated version.

Best regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
I just pushed a pre release which has this in it, a long with a first look at table creating and editing.

**Comment by devpkr1** [comment]
Hi Mike,

I hope you're doing well.

I wanted to let you know that the updated file extension for notebooks is working perfectly—thank you for making that change! I’ve also tested your prerelease with the added feature for creating and editing tables in MySQL/MariaDB.

For better clarity, I’ll open a separate issue thread regarding feedback on this new feature.

Best regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
1.3 is out now, with this change in it.

**Comment by mikeburgh** [comment]
actually, going to leave this open as a reminder to remove the old dbcode mapping in a month or so

**Comment by mikeburgh** [comment]
This is now done. closing
