### ISSUE TITLE
No hints for exec

### ISSUE THREAD

**Issue by DIMANRUS** [dbcodeio/public#45]
Hello. If I enter exec and then want to write a procedure, there are no hints, it looks like this
![image](https://github.com/user-attachments/assets/3c2c61a2-4088-45fa-9356-73c4f03d2f0c)
If it's select, it looks like this, it would be great if it was the same for exec
![image](https://github.com/user-attachments/assets/5996ed78-6291-4894-a04e-cad5d1559829)

**Comment by mikeburgh** [comment]
Will get that sorted.

**Comment by mikeburgh** [comment]
Going to close this and track it in #59
