### ISSUE TITLE
Сan't put null in a cell

### ISSUE THREAD

**Issue by DIMANRUS** [dbcodeio/public#47]
Is there a way to set a null value in a cell when viewing data? Only through UPDATE?

**Comment by mikeburgh** [comment]
You can do it by entering (null) as the value.. which is the value it shows when it's null.

But agreed.. not intuitive.. Now I have the drop down working for current_timestamp when editing a date column.. Do you think that approach would work.. eg let it show NULL as an option to enter.

**Comment by DIMANRUS** [comment]
Got it, thanks. I would find it easier to right-click on the cell and select the set to NULL button

**Comment by mikeburgh** [comment]
Keeping this open, going to add a Set Value -> Sub menu in the right click with some standard options pending on the columns config.

**Comment by mikeburgh** [comment]
Okay this is in 1.3.2, you can right click a cell and if editable with options (allows null, is an enum, is a date ) then the set value menu will appear allowing you to select a value and update the cell.
