### ISSUE TITLE
View column description

### ISSUE THREAD

**Issue by DIMANRUS** [dbcodeio/public#50]
Hello. It would be great to see a description of the column in this window as well.
![image](https://github.com/user-attachments/assets/18c1662c-8fe0-4294-ae5c-2d43920d942e)

**Comment by mikeburgh** [comment]
Do you mean the comment of the column ? 

I had it there previously, but it makes the table super wide and on some screen vs code then condenses it and breaks the wrapping.

You can only use a subset of HTML in that popup as well which makes it hard to counter. 

I might switch it to list rather than a table, then I can fit more in.

**Comment by DIMANRUS** [comment]
I mean this description for the column
![image](https://github.com/user-attachments/assets/16518302-315c-4524-b086-22fd239c0e61)
![image](https://github.com/user-attachments/assets/194e7779-e1ab-415f-9d75-05c0da7f9002)

**Comment by mikeburgh** [comment]
Ahh, I forgot MS did that differently to the others.. Let me look into picking it up.. the other DB's call it a comment.. and I grab it from those.

**Comment by mikeburgh** [comment]
Okay it's in, should be released later today pending I finish all this type and table edit work.

I also adjusted the layout, comment now appears at the top after the type int he comment... and in the table fields, you can see it here..

<img width="998" alt="Screenshot 2024-10-11 at 9 03 12 AM" src="https://github.com/user-attachments/assets/d53772ed-0ef6-46bf-ad53-12a05f915743">

<img width="690" alt="Screenshot 2024-10-11 at 9 03 17 AM" src="https://github.com/user-attachments/assets/bb4f2142-7054-431e-873c-3b0d46f28927">

Open to any suggestions on the layout.

**Comment by DIMANRUS** [comment]
Thank you very much. You really do a very useful and excellent job creating an extension for developers. I will definitely recommend your extension to my friends.

**Comment by mikeburgh** [comment]
Thanks, really appreciate that feedback!

Version 1.3 is out now with this in place.

**Comment by DIMANRUS** [comment]
Hello. Thank you, everything works fine. But there is one thing. When the descriptions are long, everything moves, but you can display, for example, the first 50 characters, and view the rest inside the table, for example (Issue #54).

**Comment by mikeburgh** [comment]
Good catch, fixed in 1.3.2 it trims it down to keep the table structure.
