### ISSUE TITLE
Columns only for the current table when writing code

### ISSUE THREAD

**Issue by DIMANRUS** [dbcodeio/public#51]
Hello. When I write a condition for select, I want to see columns only for the table that is in the select, and not for the entire database.
![image](https://github.com/user-attachments/assets/908313bb-1f6f-46d9-9916-4d2dae6ef8f8)

**Comment by mikeburgh** [comment]
Thanks, parser only shows all columns when it cannot identify the table.. I am guessing it's a case problem.. will add a fix for it in the next release hopefully later this week.

**Comment by mikeburgh** [comment]
Should be fixed now in 1.3.1

**Comment by DIMANRUS** [comment]
Thanks. It is working.
