### ISSUE TITLE
Collections in MongoDB not opening correctly

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#52]
Dear Mike,

I am reaching out to report an issue I encountered while using your extension to connect to MongoDB. Although I was able to establish a successful connection, I faced a problem when trying to open a collection that I had created in the MongoDB client. Instead of opening the collection, I received an error message.  

I have attached a screenshot of the error for your reference.
![Screenshot 2024-10-13 104040](https://github.com/user-attachments/assets/c3d3eca9-3bfe-4de8-827b-61b7c49b7ec0)
![Screenshot 2024-10-13 103947](https://github.com/user-attachments/assets/4723de52-f3f1-4976-9d7a-b76cc384a0ab)

While that collection is opening perfectly in mongoDB client
![Screenshot 2024-10-13 110226](https://github.com/user-attachments/assets/f9b78ed9-5932-4f89-9feb-ecde59f5644a)

Could you please assist me in resolving this issue?

Best regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
Yeah, bug I introduced in the pre release version.. I found it as well yesterday when finishing up the data types work and testing it... Going to push a new regular release hopefully today with that fix, and a few more of these tickets knocked down

**Comment by mikeburgh** [comment]
1.3 is out now, with this fix
