### ISSUE TITLE
MongoDB commands are not working in DBCode Notebooks

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#55]
Hi Mike,

I have tried to write mongoDB commands in DB code Notebooks and found that its not working there .

I am attaching the screenshot for your reference , please have a look into this issue.
![Screenshot 2024-10-14 112306](https://github.com/user-attachments/assets/f30b7280-52b2-48d4-a537-5c6f38da42e9)

Thanks & regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
I had this on the list for awhile... was waiting to see if anyone wanted to use it.

I just pushed a first version of it in 1.3.2. Let me know how it goes for you, what else you would want to do etc..  Mongo is not a DB I have used much so not sure what makes sense to be possible there.

Also, no autocomplete for this at this stage... need to come up with a way for that to work..

**Comment by devpkr1** [comment]
Hi Mike,

Its now working in this release.

Thanks again for your kind support.

**Comment by mikeburgh** [comment]
Great, I will close this for now, but I expect more work needed here once I get an idea of what people want to do with it.. for now it's very basic.
