### ISSUE TITLE
Table suggestion is not working while writing  sql statements

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#56]
Hi Mike,

I found that after your recent update the table suggestion is not working while writing SQL statements, please have a look into this .

![Screenshot 2024-10-14 114431](https://github.com/user-attachments/assets/5d089c2e-8eb0-49aa-b84f-e726bdb668ed)

Thanks and Regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
Ironic.. the notebook side was checking the file extension, not just the language in the cell.. and it was still .dbcode. Removed that check so it's now consistent with the editor and just looking at the language. Will be fixed in next release

**Comment by devpkr1** [comment]
Thank you so much Mike

**Comment by mikeburgh** [comment]
Fixed in 1.3.2 which is now released
