### ISSUE TITLE
Hints for naming tables in the code do not work

### ISSUE THREAD

**Issue by DIMANRUS** [dbcodeio/public#57]
Hello. If I work with join, then I assign, for example, a letter to each table, but hints do not work through the letter.
That's how it works
![Image](https://github.com/user-attachments/assets/a69e0ddd-32d2-4189-9891-b8d1d1903934)
And it doesn't work like that
![Image](https://github.com/user-attachments/assets/3681c98f-41fb-40bc-8c91-f8ecdafdb18a)

**Comment by mikeburgh** [comment]
Yeap, I have created a new catch all issue for this stuff, so it's clear what's covered at the moment and what's not.

So can keep track and post issues there: #59 

I added Aliases support under select.
