### ISSUE TITLE
d1 unknown data type string

### ISSUE THREAD

**Issue by autist-me** [dbcodeio/public#64]
![Image](https://github.com/user-attachments/assets/ab826c39-cd7f-4aa9-98fe-cbe592363770)

seems Cloudflare only accept 4 types...

Tipo de datos desconocido string en _FOO-TABLE_ (Cloudflare)

Error:
Unknown type string

---
VSCode Version: 1.94.2
Extension Version: 1.3.2
OS: linux
Arch: x64
Database Version: WEUR - 

![Image](https://github.com/user-attachments/assets/68a410dd-73fa-4b3b-b0fb-948e2109c0da)

**Comment by mikeburgh** [comment]
Yes, D1 is built on top of SQLite, which only has 5 main datatypes: https://www.sqlite.org/datatype3.html

But it allows you to put a lot of other common datatype names into field definitions, and there are some rules about how it maps those back to it's main types (3.1 section of that url).

I had not seen string or number in my testing, so I will get those added and mapped so the errors stop coming up.

If you check out the create/alter table feature I am working on in the extension you can see I have the expanded list, but underneath they are all just that same 4 cloudflare shows.

Thanks for raising the issue and the helpful screenshots, should get this fix released today

**Comment by mikeburgh** [comment]
Version 1.3.2 is out now, has these types added.
