### ISSUE TITLE
Issue with "Apply Changes" Button in Alter table and Create table

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#68]
Hi Mike,

I hope you're doing well.

I've noticed that the SQL Preview is functioning correctly when using the "Alter Table" and "Create Table" options from the context menu. However, the "Apply Changes" button does not seem to be working during these operations, whether altering an existing table or creating a new one.

Please find the attached screenshot for reference.

![Image](https://github.com/user-attachments/assets/02da78ab-0dce-4e58-bca3-7af92eb45b01)
![Image](https://github.com/user-attachments/assets/22722f82-ddbb-4e9b-b5e2-443a40507d70)

Thanks and best regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
Indeed, I was rushing to get it out and broke it with the last change. Fixed now.. it was basically just previewing when you clicked the button.

New version out with the fix.
