### ISSUE TITLE
mysql connection error

### ISSUE THREAD

**Issue by Karim129** [dbcodeio/public#69]
Error:
getaddrinfo EAI_AGAIN root

---
VSCode Version: 1.94.2
Extension Version: 1.3.7
OS: linux
Arch: x64

**Comment by mikeburgh** [comment]
Usually this means there was a DNS error with the host name you are using. Can you make sure it was correct and resolving ?

**Comment by mikeburgh** [comment]
Closing, re open if you are still having issues.
