### ISSUE TITLE
MongoDB connection without credentials

### ISSUE THREAD

**Issue by rahbari** [dbcodeio/public#70]
Can't create a MongoDB connection without username and password. My local server neither has nor needs a password.

![Image](https://github.com/user-attachments/assets/85859803-ae55-4d7f-96c7-907158282fc9)

Error:
authMechanism DEFAULT not supported

---
VSCode Version: 1.94.2
Extension Version: 1.3.7
OS: darwin
Arch: arm64

**Comment by mikeburgh** [comment]
How did you config the mongo DB to not require a username and password but till be able to perform actions ?

In my testing I have been able to connect without them, but then any action (like listing databases) will fail cause the connection is not authenticated. 

I just want to setup a test enviroment that matches yours to make sure I get it working without the login details properly.

**Comment by rahbari** [comment]
I installed MongoDB v8 using brew, by default it does not have username or password.
![Image](https://github.com/user-attachments/assets/9ade74b7-3592-4d49-9e0b-3557cfcdaf1b)
in compass these settings are optional, and it works.

**Comment by mikeburgh** [comment]
Perfect.. Yes I saw they were optional, but I could not get a mongo install that set them as optional when I was trying in docker or via the various cloud providers.

Let me spin a brew install, make sure the extension works properly without the username (At the moment it connects, but I get the error about not authorized, figure that will change once I connect to the brew install) and then I will include the change in todays release and update this issue when it's released

**Comment by mikeburgh** [comment]
Version 1.3.10 is out and fixes this
