### ISSUE TITLE
Request for Context Menu Enhancement for Group

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#73]
Hi Mike,

I hope you're doing well.

If possible, could you please add a right-click context menu option for renaming a group? This feature would enhance usability and streamline the process for users.

Thank you for considering this request.

Best regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
Indeed.. it's now there, will be in the next release.

It is added in both the context menu, and the inline edit icon that appears (next to the remove one).

Will update when live.

**Comment by mikeburgh** [comment]
Should be there now in 1.3.11, re open if you find any issues.
