### ISSUE TITLE
mysql introspection error

### ISSUE THREAD

**Issue by EndyPratama** [dbcodeio/public#74]
Error:
FUNCTION JSON_ARRAYAGG does not exist

---
VSCode Version: 1.94.2
Extension Version: 1.3.10
OS: win32
Arch: x64
Database Version: mariadb.org binary distribution - 10.4.32-MariaDB

**Comment by mikeburgh** [comment]
Thanks, should be fixed now in 1.3.11 if you upgrade to that version.
