### ISSUE TITLE
D1 - not show views

### ISSUE THREAD

**Issue by autist-me** [dbcodeio/public#75]
At tree and from notebook , can't show views:

![Image](https://github.com/user-attachments/assets/75a37f1d-9a93-4787-bacc-da8ec99ebbe7)

Console Cloudflare:

![Image](https://github.com/user-attachments/assets/2c37bce8-d464-4e4f-8a19-6e0a91c6e06e)

**Comment by mikeburgh** [comment]
Thanks, good find. Will get it fixed and update when it's released.

**Comment by mikeburgh** [comment]
1.3.11 was just released, this should be fixed now if you upgrade to that version
