### ISSUE TITLE
Context Menu Customization Suggestions for Database ("Show Tables" and "Count Tables")

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#78]
Hi Mike,

I hope this message finds you well.

I wanted to share a couple of suggestions for enhancing the context menu for the database feature. I believe these additions would significantly improve user experience:

**Show Tables:** When a user selects this option, it would display a list of tables within the database, along with the number of records for each table in the main area.

**Count Tables:** This option would provide the total number of tables in the database, also displayed in the main area.

I think these changes would make the extension more user-friendly. If you find these suggestions valuable, I would appreciate it if you could implement them. I've attached a screenshot for your reference.

![Image](https://github.com/user-attachments/assets/67712684-a622-4221-9553-a5cea00ba63f)

Thank you for considering these enhancements!

Best regards,
Pradeep

**Comment by mikeburgh** [comment]
I just added the count of items in the DB Explorer for tables, views, procs, columns etc.. what do you think ? feels a little busy.. but I am open to feedback on if it should stay/go or become a setting.

**Comment by devpkr1** [comment]
Thank you for your feedback on this suggestion! It’s looking great now. I can see the count of tables directly in the DB Explorer. Overall, it looks really good at this point, so let’s proceed with this.

**Comment by mikeburgh** [comment]
Okay I will close this for now. See if there are other use cases for showing a list of tables and row counts in the main window

**Comment by devpkr1** [comment]
Sure,  I’ll keep an eye out for any other use cases where displaying a list of tables and row counts in the main window could add value.
