### ISSUE TITLE
Charts Settings Missing

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#80]
Hi Mike,

I hope this message finds you well.

I wanted to bring to your attention an issue I’ve encountered with the chart settings. It seems that the settings are not displaying when I create charts, and I’m unable to access them from the side panel.

I’ve attached some screenshots for your reference. Could you please take a look at this ?

![Image](https://github.com/user-attachments/assets/3f755200-de1a-40ec-8f13-a5bb57a642cd)

Thank you!

Best regards,
Pradeep

**Comment by mikeburgh** [comment]
Yeah I can see the error, but it's deep inside the chart object, and nothing I have changed recently effects that. I am almost finished upgradeing to their newer version.. will see if that fixes it.. if not I will dig deeper

**Comment by mikeburgh** [comment]
Fixed in 1.3.15 which was just released. The kebab menu at the top right now lets you edit the chart and other features.
