### ISSUE TITLE
mssql introspection error

### ISSUE THREAD

**Issue by mferris77** [dbcodeio/public#81]
Hi there - I was checking out this extension - it looks very promising!  I set up a connection to a MS SQL server and can see all of the databases I expect to see.  However when I try to expand one of the databases, I get this 'introspection' error saying "Invalid column name 'is_enforced'.  I'm not sure where that comes from as it occurs on every database I try to look at.

The SQL Server is Microsoft SQL Server 2016 SP3 - perhaps 'is_enforced' is a feature not available on this older version?  

I did search for this error but didn't find anything - hope this is enough information to debug - if not I can provide whatever might be helpful to further investigate.

Thanks

Error:
Invalid column name 'is_enforced'.

---
VSCode Version: 1.95.0-insider
Extension Version: 1.3.13
OS: win32
Arch: x64
Database Version: Microsoft SQL Server 2016 (SP3) (KB5003279) - 13.0.6300.2 (X64)  Aug  7 2021 01:20:37  Copyright (c) Microsoft Corporation Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)  - Standard Edition (64-bit) - 13.0.6300.2

**Comment by mikeburgh** [comment]
Thanks, that information is perfect… and I am guessing you are right it might not be present in 2016. I will spin up a test db to confirm and push a fix once confirmed that's what it is.

**Comment by mikeburgh** [comment]
I just released version 1.3.14, it should fix this issue..  Let me know how you go.

**Comment by mikeburgh** [comment]
Closing this, let me know if you still have issues
