### ISSUE TITLE
Request for New Database Support - Apache Cassandra

### ISSUE THREAD

**Issue by mohdWajid19** [dbcodeio/public#83]
Hi Team, first of all thanks for creating this extension this is making development so much easier.

Description:
I would like to request the addition of Apache Cassandra database support to the DB-tools VS Code extension.

Technical Details:
- Database Type: Apache Cassandra
- Connection Requirements:
  * Host/Contact points
  * Port (default: 9042)
  * Authentication credentials (username/password)
  * Local datacenter name
  * SSL/TLS support (if applicable)

Expected Features:
1. Database Connection Management
   - Ability to save and manage multiple connection profiles
   - Support for secure credential storage

2. Query Capabilities
   - CQL query execution
   - Query result visualization
   - Query history

3. Database Explorer
   - Browse keyspaces
   - View tables and their schemas
   - View indexes and materialized views

4. Additional Features (Optional)
   - Schema visualization
   - Data export/import capabilities
   - Query performance analysis

Thank you for considering this feature request.

**Comment by mikeburgh** [comment]
Wow, thanks for the super helpful detail. I have a couple of other DB's I am working on, but will get this on the list. I will reach out once it's ready so you can give it a test.

**Comment by mikeburgh** [comment]
I just pushed a pre release version with support for Cassandra. Would you mind trying it out and letting me know you feedback ?<br><br>One thing I think I might change, at the moment the keyspaces are being represented as databases, which is not really correct, they are more like schemas. So I might re work that and use the Cluster name as the database, and show the schemas under that (at the moment I have to have a database, I don't think I can skip straight to schemas).

**Comment by mohdWajid19** [comment]
Thank you for considering the request. I have tested the pre-release version `v1.3.19` and successfully connected to my local Cassandra instance. It appears to be functioning exceptionally well; I executed several queries without any issues. I also tested the ER diagram feature, but encountered a blank page (PFA) , likely  due to Cassandra's distributed and denormalized nature. Overall, I am very pleased with its performance.

![Image](https://github.com/user-attachments/assets/bfca7f9d-66f0-44d0-85ca-fb7a9af179b8)

**Comment by mikeburgh** [comment]
Thanks for confirming.

Interesting on the ERD.. it should still show the tables, it just does not know how to connect them as there are no foreign keys... so should look something like..

[Image](https://github.com/user-attachments/assets/ac14a907-ab7a-44ab-b398-edb95a290569)


Can you check the console (Help -> Developer tools) and see if there is anything shown there after you try and open the window ? 

I still plan to implement import and query performance/plan but that will come when it's added to the extension for all databases that support it.

**Comment by mikeburgh** [comment]
Going to close this, re open if you are still having issues with the ERD and can share those logs
