### ISSUE TITLE
mssql unknown data type: timestamp

### ISSUE THREAD

**Issue by hasokeric** [dbcodeio/public#87]
Error:
Unknown type timestamp

---
VSCode Version: 1.96.0-insider
Extension Version: 1.3.15
OS: win32
Arch: x64
Database Version: Microsoft SQL Server 2019 (RTM-CU19) (KB5023049) - 15.0.4298.1 (X64)  Jan 27 2023 16:44:09  Copyright (C) 2019 Microsoft Corporation Standard Edition (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: ) (Hypervisor)  - Standard Edition (64-bit) - 15.0.4298.1

**Comment by mikeburgh** [comment]
Version 1.3.16 has this fix in it
