### ISSUE TITLE
mysql connection error

### ISSUE THREAD

**Issue by Jokaes** [dbcodeio/public#88]
Error:
MySQL 5.7 or higher is required

---
VSCode Version: 1.95.0
Extension Version: 1.3.15
OS: win32
Arch: x64

**Comment by mikeburgh** [comment]
What is the version of MySQL you are trying to connect to? At present we only support 5.7 and above. Running this will show you the version: 

```sql
select version()
```

**Comment by mikeburgh** [comment]
Closing this for now, re open if it's a version above 5.7
