### ISSUE TITLE
Data Display Issue in Version 1.3.16

### ISSUE THREAD

**Issue by rifatdinc** [dbcodeio/public#90]
**Issue Summary**

In version 1.3.16, data is not displayed as expected. However, the same data appears correctly in version 1.3.15.

	1.	Use version 1.3.15 to display data – data shows correctly (see Screenshot 1).
	2.	Switch to version 1.3.16 – data is missing (see Screenshot 2).

Environment

	•	Version: 1.3.15 (working) and 1.3.16 (not working)
	•	Operating System: MacOS M3 Macbook Pro
	•	VsCode Version : Version: 1.95.0 (Universal)
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:16:24.561Z (2 days ago)
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.0.0.

![Image](https://github.com/user-attachments/assets/a217e804-1373-482f-931e-941925a5266b)
![Image](https://github.com/user-attachments/assets/39007249-221e-44ba-b7b0-649cb46a61e0)

**Comment by mikeburgh** [comment]
Thanks for the speedy submission and all the detail.

Found the issue, pushing a fix now.. should be released to the marketplace shortly.

**Comment by mikeburgh** [comment]
Fix is live, confirmed working
