### ISSUE TITLE
Context Menu: Add to Group

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#97]
Hi Mike,

I have a few suggestions regarding the database connection context menu that could enhance usability, especially around grouping connections.

Firstly, I suggest adding an option, "Add to Group", in the context menu. This option could then have a submenu with choices like "Create New Group" and a list of Existing Groups to add connections to.

I believe this feature would significantly improve the user interface of the extension. I've attached a screenshot for your reference.

![Image](https://github.com/user-attachments/assets/ea7a8d24-acdc-4e8c-9026-6f54ae3dacd3)

Thanks for considering this enhancement!

Best regards,
Pradeep

**Comment by mikeburgh** [comment]
I have re worked the group feature, so you can now group single connections, and added a right click option to connections for Add to Group.

You cannot do dynamic context  menus in vscode, so it loads a quick pick input to select an existing group or enter the name for one.

i also re worked removing from a group to support multiple items

Will update this when it gets released

**Comment by devpkr1** [comment]
Hi Mike,

Thank you for the update on the group feature enhancements! I'm excited to hear about the ability to group single connections and the new right-click option for adding connections to groups. The implementation of a quick pick input for selecting or creating groups sounds like a user-friendly solution.

I'm also glad to hear that the removal process has been improved to support multiple items—this will definitely streamline the workflow.

Looking forward to seeing these updates in action once they are released.

Best regards,
Pradeep

**Comment by mikeburgh** [comment]
This is now live in 1.4.11
